/**
 * Webpack Configuration for Medical Academic Theme
 *
 * Extends @wordpress/scripts webpack configuration with custom settings for theme development.
 * Handles JavaScript compilation, Sass to CSS conversion, code minification, and asset bundling.
 *
 * Features:
 * - Compilation: Babel transforms ESNext and JSX syntax into browser-compatible code
 * - Bundling: Webpack combines multiple JavaScript files into optimized bundles
 * - Sass Compilation: Converts .scss files to standard CSS
 * - Code Minification: Terser (JS) and cssnano (CSS) minify production builds
 * - Asset Optimization: Images and fonts are processed and optimized
 * - Source Maps: Generated for easier debugging in development
 * - Hot Module Replacement: Enables fast refresh during development
 *
 * @see https://developer.wordpress.org/themes/advanced-topics/build-process/
 * @see https://developer.wordpress.org/block-editor/getting-started/devenv/get-started-with-wp-scripts/
 *
 * @package
 * @since 1.0.0
 */

// WordPress webpack configuration.
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

// Plugins.
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');

// Node modules.
const path = require('path');

// Define custom entry points for theme assets.
module.exports = {
	...defaultConfig,

	/**
	 * Entry points for the build process.
	 * Each entry point generates a separate bundle with an accompanying .asset.php file.
	 */
	entry: {
		// Frontend JavaScript.
		'js/theme': path.resolve(process.cwd(), 'src/js', 'theme.js'),
		// Editor JavaScript.
		'js/editor': path.resolve(process.cwd(), 'src/js', 'editor.js'),
		// Frontend styles (Sass).
		'css/style': path.resolve(process.cwd(), 'src/css', 'style.scss'),
		// Editor styles (Sass).
		'css/editor-style': path.resolve(
			process.cwd(),
			'src/css',
			'editor.scss'
		),
	},

	/**
	 * Output configuration.
	 * Defines where the compiled files will be placed.
	 */
	output: {
		...defaultConfig.output,
		path: path.resolve(process.cwd(), 'build'),
		filename: '[name].js',
		clean: true,
	},

	/**
	 * Module rules for processing different file types.
	 * Extends wp-scripts default rules with custom configurations.
	 */
	module: {
		...defaultConfig.module,
		rules: [
			// Include all default wp-scripts rules.
			...defaultConfig.module.rules,

			// Additional rule for handling images.
			{
				test: /\.(png|jpe?g|gif|svg|webp)$/i,
				type: 'asset/resource',
				generator: {
					filename: 'images/[name][ext]',
				},
			},

			// Additional rule for handling fonts.
			{
				test: /\.(woff|woff2|eot|ttf|otf)$/i,
				type: 'asset/resource',
				generator: {
					filename: 'fonts/[name][ext]',
				},
			},
		],
	},

	/**
	 * Module resolution configuration.
	 * Adds custom path aliases for cleaner imports.
	 */
	resolve: {
		...defaultConfig.resolve,
		alias: {
			...defaultConfig.resolve.alias,
			'@': path.resolve(__dirname, 'src'),
			'@css': path.resolve(__dirname, 'src/css'),
			'@js': path.resolve(__dirname, 'src/js'),
		},
	},

	/**
	 * Optimization configuration.
	 * Controls code splitting and minification.
	 */
	optimization: {
		...defaultConfig.optimization,
		// Minification is automatically handled by wp-scripts based on NODE_ENV.
		// In production mode, JavaScript is minified using Terser.
		// CSS is minified using cssnano via postcss.
	},

	/**
	 * Plugins configuration.
	 * Extends default wp-scripts plugins with theme-specific additions.
	 */
	plugins: [
		// Include all default wp-scripts plugins.
		...defaultConfig.plugins,

		// Removes empty .js files generated by webpack for CSS-only entry points.
		// Must run after WP has generated its *.asset.php files.
		// @see https://developer.wordpress.org/themes/advanced-topics/build-process/
		new RemoveEmptyScriptsPlugin({
			stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
		}),
	],

	/**
	 * Performance hints configuration.
	 * Warns if assets exceed size limits.
	 */
	performance: {
		...defaultConfig.performance,
		maxAssetSize: 512000, // 500 KB.
		maxEntrypointSize: 512000, // 500 KB.
		hints: process.env.NODE_ENV === 'production' ? 'warning' : false,
	},

	/**
	 * Development server configuration.
	 * Enables hot module replacement for faster development.
	 */
	devServer: {
		...defaultConfig.devServer,
		hot: true,
		liveReload: true,
	},
};
